'''This is an environmentally responsive cellular automaton. It is under very early development. For this to work properly you will need a device that can provide information about the current environment. This was developed using an arduino (http://www.arduino.cc/) with a light sensitive resistor (the circuit used can be found here: http://www.ladyada.net/learn/sensors/cds.html). If you do not have an arduino or a similar device, the module will still work; although it will not behave the same as when using an arduino. In such a case, the module works by catching the exceptions generated by the lack of an arduino, and generating random data through  enviro=random.randint(0,1000).

The rules for the automaton are derived from Conways game of life. This code is incomplete and currently needs to be integrated with birdcage topology, neighbourhood and visuals.

Written by Diego January 2010'''

# Import the necessary modules
import Image
import ImageDraw
import random
import serial


def getEnvironment(port):
	""" Gets a reading from the environment sensor. In case there is no such
	device, prints a notification of such a lack.
	"""
	## The try except clause is used in order to be able to run the code
     # without an arduino interface.
	try:
		sensor =  serial.Serial(str(port), 9600)
		environment = []
		# loop until a reading is received.
		while len(environment) < 1:
			environment = sensor.readline()
			environment = environment.split()
		try:
			environment = int(environment[0])
		except ValueError:
			getEnvironment(port)
	except serial.serialutil.SerialException:
		print 'No serial reading!!! using random environment.'
		environment=random.randint(0,1000)
	return environment

def initials(fractON, side, environment):
	'''Generates the initial condition of the automaton, it requires a 
	proportion of initially living individuals, the length of the sides of the
	automaton and a serial port to read the sensors.
	'''
	espacio = [0]*(side**2)
	onindivs = (side**2)*fractON    
	'''Set up living and dead'''
	for i in range(0,int(onindivs)):
		espacio[random.randint(0,len(espacio)-1)] = environment
	for i in range(0,side):
		for j in range(0,side):
			if espacio[(side*i)+j] == 0:
				espacio[(side*i)+j] = random.randint(1,1000)
	print "percentage living = %d, #of cells = %d,#of living %d" %(fractON*100,len(espacio),len(espacio)*fractON)
	return espacio

def visuals(input_list,side,environment,generation):
	'''This module generates all the visual data of the automaton as still
	images, this module is under development and will hopefully be substituted
	by abirdcage visuals  module to allow realtime playback of the automaton. It
	requires a list of states for each pixel, the dimensions of the sides
	(currently it only draws squares) an environmental condition and a
	generation number.
	'''
	im = Image.new("RGB",(side,side))
	draw = ImageDraw.Draw(im)
	for i in range(0,side):
		for j in range(0,side):
			if input_list[(side*i)+j]-5<= environment <= input_list[(side*i)+j]+5:
				draw.point((i,j),(255,255,0))
			else:
				draw.point((i,j),(0,0,255))
	im.save("generacion"+str(generation)+".tiff")

def updateRule(input_list,side,environment):
     espacio2 ={}
     print environment
     for cell in input_list:
          print cell
          if abs(abs(cell) - environment) <= 5:
               cell = abs(cell)
          else:
    	          cell = -abs(cell)
    	
     for i in range(0,side):
          for j in range(0,side):
               ONneighbors = 0
               if (side-1)>i>0 and (side-1)>j>0:
                    for (k,l) in [(-1,-1), (-1,0), (-1,1), (0,-1), (0,1), (1,-1), (1,0), (1,1)]:
                         if input_list[(side*(i+k)) + (j+l)] >= 0:
                              ONneighbors = ONneighbors + 1
                    #print ONneighbors
                    if input_list[(side*i) + j] >= 0:
                         if 2 <= ONneighbors <= 3:
                              espacio2[i,j] = environment
                         elif (input_list[(side*i)+j]-environment) > 0:
                              espacio2[i,j] = environment - 15
                         elif (input_list[(side*i)+j]-environment) < 0:
                              espacio2[i,j] = environment + 15
                         else:
                              if input_list[(side*i)+j]<500:
                                   espacio2[i,j]= environment+15
                              if input_list[(side*i)+j]>500:
                                   espacio2[i,j]= environment-15
                    	
               else:
                    if ONneighbors == 3:
                         espacio2[i,j] = environment
                    else:
                        espacio2[i,j]= (abs(input_list[(side*i)+j]))

     for i in range(1,side-1):
          for j in range(1,side-1):
               input_list[(side*i)+j] = espacio2[i,j]
    
     return input_list 
           


sideL = 100
environment = getEnvironment('/dev/ttyUSB0')
cells = initials(0.15,sideL,environment)

for time in range(0,300):
	visuals(cells,sideL,environment,time)
	cells = updateRule(cells,sideL,environment)
	environment = getEnvironment('/dev/ttyUSB0')
	#print time,environment

