#!/usr/bin/python
'''This is an environmentally responsive cellular automaton. It is under very early development. For this to work properly you will need a device that can provide information about the current environment. This was developed using an arduino (http://www.arduino.cc/) with a light sensitive resistor (the circuit used can be found here: http://www.ladyada.net/learn/sensors/cds.html). If you do not have an arduino or a similar device, the module will still work; although it will not behave the same as when using an arduino. In such a case, the module works by catching the exceptions generated by the lack of an arduino, and generating random data through  environment=random.randint(100,1000).

The rules for the automaton are derived from Conways game of life. This code is incomplete and currently needs to be integrated with birdcage topology, neighbourhood and visuals. This particualr version explores the creation of a viewer through pyGame.

Written by Diego (aka 5inister) January 2010'''

# Import the necessary modules

import random
import pyGameVisual
from lib_environment import updateRule
from lib_environment import getEnvironment

def initials(fractON, side, environment):
	'''Generates the initial condition of the automaton, it requires a 
	proportion of initially living individuals, the length of the sides of the
	automaton and a serial port to read the sensors.
	'''
	automaton = [0]*(side**2)#Generate the automaton
	onindivs = (side**2)*fractON    
	#Set up living and dead
	for i in range(0,int(onindivs)):
		automaton[random.randint(0,len(automaton)-1)] = environment
	for i in range(0,side):
		for j in range(0,side):
			if automaton[(side*i)+j] == 0:
				automaton[(side*i)+j] = random.randint(1,1000)
	print "percentage living = %d, #of cells = %d,#of living %d" %(fractON*100,len(automaton),len(automaton)*fractON)
	return automaton


#-#-#-#-#-#-#-#-#-# Run the program #-#-#-#-#-#-#-#-#-#
           
sideL = 100                                  #Define the automaton's dimensions
environment = getEnvironment('/dev/ttyUSB0') #Initialize environment
cells = initials(0.15,sideL,environment)     #Initialize the automaton (create generation 0)

viewer = pyGameVisual.PyGVisual()

while True:
	viewer.generate(cells,environment)
	viewer.update()
	viewer.viewClose()
	cells = updateRule(cells,sideL,environment)
	environment = getEnvironment("/dev/ttyUSB0")
	print environment


