/* Generated by Pyrex 0.9.6.4 on Wed May  7 09:49:12 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from topology */

enum  {
  __pyx_e_8topology_caliber = 1000
};

struct __pyx_obj_8topology_Topology {
  PyObject_HEAD
  struct __pyx_vtabstruct_8topology_Topology *__pyx_vtab;
  int dimension;
  int background;
  int cells;
  PyObject *size;
  PyObject *zero;
  PyObject *name;
};

struct __pyx_obj_8topology_GridTopology {
  struct __pyx_obj_8topology_Topology __pyx_base;
  int border;
  int width;
  int height;
  int cell[__pyx_e_8topology_caliber][__pyx_e_8topology_caliber];
};

struct __pyx_obj_8topology_ToroidTopology {
  struct __pyx_obj_8topology_GridTopology __pyx_base;
};


struct __pyx_vtabstruct_8topology_Topology {
  int (*pyx_isNormalized)(struct __pyx_obj_8topology_Topology *,PyObject *);
  PyObject *(*pyx_normalize)(struct __pyx_obj_8topology_Topology *,PyObject *);
};
static struct __pyx_vtabstruct_8topology_Topology *__pyx_vtabptr_8topology_Topology;


struct __pyx_vtabstruct_8topology_GridTopology {
  struct __pyx_vtabstruct_8topology_Topology __pyx_base;
  int (*normal_x1)(struct __pyx_obj_8topology_GridTopology *,int);
  int (*normal_x2)(struct __pyx_obj_8topology_GridTopology *,int);
  int (*pyx_get)(struct __pyx_obj_8topology_GridTopology *,int,int);
  int (*pyx_get_nosafe)(struct __pyx_obj_8topology_GridTopology *,int,int);
  int (*pyx_set)(struct __pyx_obj_8topology_GridTopology *,int,int,int);
  void (*pyx_set_nosafe)(struct __pyx_obj_8topology_GridTopology *,int,int,int);
};
static struct __pyx_vtabstruct_8topology_GridTopology *__pyx_vtabptr_8topology_GridTopology;


struct __pyx_vtabstruct_8topology_ToroidTopology {
  struct __pyx_vtabstruct_8topology_GridTopology __pyx_base;
};
static struct __pyx_vtabstruct_8topology_ToroidTopology *__pyx_vtabptr_8topology_ToroidTopology;

static PyTypeObject *__pyx_ptype_8topology_Topology = 0;
static PyTypeObject *__pyx_ptype_8topology_GridTopology = 0;
static PyTypeObject *__pyx_ptype_8topology_ToroidTopology = 0;

/* Declarations from neighborhood */

enum  {
  __pyx_e_12neighborhood_capacity = 20
};

struct __pyx_obj_12neighborhood_Neighborhood_2D {
  PyObject_HEAD
  struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *__pyx_vtab;
  struct __pyx_obj_8topology_GridTopology *topology;
  int neighbors;
  PyObject *name;
  int neighbors_x1[__pyx_e_12neighborhood_capacity];
  int neighbors_x2[__pyx_e_12neighborhood_capacity];
  int neighbors_st[__pyx_e_12neighborhood_capacity];
};

struct __pyx_obj_12neighborhood_VonNeumannNeighborhood {
  struct __pyx_obj_12neighborhood_Neighborhood_2D __pyx_base;
};


struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D {
  struct __pyx_obj_12neighborhood_Neighborhood_2D *(*pyx_clone)(struct __pyx_obj_12neighborhood_Neighborhood_2D *);
  void (*pyx_calculateNeighbors)(struct __pyx_obj_12neighborhood_Neighborhood_2D *,int,int);
  void (*pyx_calculateStates)(struct __pyx_obj_12neighborhood_Neighborhood_2D *,int,int);
  int (*pyx_reduceStates)(struct __pyx_obj_12neighborhood_Neighborhood_2D *,int,int,PyObject *,int);
  int (*pyx_sumStates)(struct __pyx_obj_12neighborhood_Neighborhood_2D *,int,int);
};
static struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *__pyx_vtabptr_12neighborhood_Neighborhood_2D;


struct __pyx_vtabstruct_12neighborhood_VonNeumannNeighborhood {
  struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D __pyx_base;
};
static struct __pyx_vtabstruct_12neighborhood_VonNeumannNeighborhood *__pyx_vtabptr_12neighborhood_VonNeumannNeighborhood;

static PyTypeObject *__pyx_ptype_12neighborhood_Neighborhood_2D = 0;
static PyTypeObject *__pyx_ptype_12neighborhood_VonNeumannNeighborhood = 0;


/* Implementation of neighborhood */


static PyObject *__pyx_n_exceptions_birdcage;
static PyObject *__pyx_n_E;
static PyObject *__pyx_n_operator;

static PyObject *__pyx_n_DimensionError;

static PyObject *__pyx_k3p;

static char __pyx_k3[] = "Abstract 2D neighborhood system";

static int __pyx_f_12neighborhood_15Neighborhood_2D___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_12neighborhood_15Neighborhood_2D___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8topology_GridTopology *__pyx_v_topology = 0;
  int __pyx_v_i;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"topology",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_topology)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF((PyObject *)__pyx_v_topology);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_topology), __pyx_ptype_8topology_GridTopology, 1, "topology")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":40 */
  Py_INCREF(((PyObject *)__pyx_v_topology));
  Py_DECREF(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology));
  ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology = __pyx_v_topology;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":41 */
  ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":42 */
  Py_INCREF(__pyx_k3p);
  Py_DECREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->name);
  ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->name = __pyx_k3p;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":44 */
  __pyx_1 = (!(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.dimension == 2));
  if (__pyx_1) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_E); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_DimensionError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.dimension); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_INCREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->name);
    PyTuple_SET_ITEM(__pyx_5, 0, ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->name);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
    __pyx_2 = 0;
    __pyx_4 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":47 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_e_12neighborhood_capacity; ++__pyx_v_i) {

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":48 */
    (((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_x1[__pyx_v_i]) = 0;

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":49 */
    (((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_x2[__pyx_v_i]) = 0;

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":50 */
    (((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_st[__pyx_v_i]) = 0;
  }

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF((PyObject *)__pyx_v_topology);
  return __pyx_r;
}

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_handleTopology(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_handleTopology[] = "Return the underlying topology, for direct\n          manipulation from Python code\n\n          return -->> a GridTopology object";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_handleTopology(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology));
  __pyx_r = ((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_clone(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_clone[] = "Make a morphologically identical copy of the grid.\n\n          return -->> a birdcage Neighborhood object\n\n          This is intended for cellular automata which require a working\n          copy of themselves, such as synchronous automata (the most\n          common kind).";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_clone(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = ((PyObject *)((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->__pyx_vtab)->pyx_clone(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.clone");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_clone;

static struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_f_12neighborhood_15Neighborhood_2D_pyx_clone(struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_v_self) {
  struct __pyx_obj_8topology_Topology *__pyx_v_topology_copy;
  struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_topology_copy = ((struct __pyx_obj_8topology_Topology *)Py_None); Py_INCREF(Py_None);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":80 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_self->topology), __pyx_n_clone); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_8topology_Topology)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_topology_copy));
  __pyx_v_topology_copy = ((struct __pyx_obj_8topology_Topology *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":81 */
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_topology_copy));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_topology_copy));
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_12neighborhood_Neighborhood_2D), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_12neighborhood_Neighborhood_2D)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_r = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)Py_None); Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.pyx_clone");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_topology_copy);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_InvalidAddressError;
static PyObject *__pyx_n_append;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_listNeighbors(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_listNeighbors[] = "List all of a given cell\'s neighbors\n\n          address ---> a Python 2-tuple, the address of a cell in the grid\n          return  -->> a Python list of coordinates, consisting of all\n                       of the cell\'s neighbours";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_listNeighbors(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  int __pyx_v_i;
  int __pyx_v_x1;
  int __pyx_v_x2;
  PyObject *__pyx_v_coordinates;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_v_coordinates = Py_None; Py_INCREF(Py_None);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":94 */
  __pyx_1 = PyObject_Length(__pyx_v_address); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = (!(__pyx_1 == 2));
  if (__pyx_2) {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_E); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_InvalidAddressError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_INCREF(__pyx_v_address);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_address);
    Py_INCREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    PyTuple_SET_ITEM(__pyx_3, 1, ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":97 */
  __pyx_4 = PyList_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_v_coordinates);
  __pyx_v_coordinates = __pyx_4;
  __pyx_4 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":99 */
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_5 = PyObject_GetItem(__pyx_v_address, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_address, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_6 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->__pyx_vtab)->pyx_calculateNeighbors(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self),__pyx_2,__pyx_6);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":101 */
  __pyx_2 = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":102 */
    __pyx_v_x1 = ((struct __pyx_vtabstruct_8topology_GridTopology *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.__pyx_vtab)->normal_x1(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology,(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_x1[__pyx_v_i]));

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":103 */
    __pyx_v_x2 = ((struct __pyx_vtabstruct_8topology_GridTopology *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.__pyx_vtab)->normal_x2(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology,(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_x2[__pyx_v_i]));

    /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":104 */
    __pyx_5 = PyObject_GetAttr(__pyx_v_coordinates, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_x1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_x2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_3);
    __pyx_4 = 0;
    __pyx_3 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":106 */
  Py_INCREF(__pyx_v_coordinates);
  __pyx_r = __pyx_v_coordinates;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.listNeighbors");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_coordinates);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static void __pyx_f_12neighborhood_15Neighborhood_2D_pyx_calculateNeighbors(struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_v_self,int __pyx_v_x1,int __pyx_v_x2) {
  Py_INCREF(__pyx_v_self);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_listStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_listStates[] = "List the states of all of a given cell\'s neighbors\n\n          address ---> a Python 2-tuple, the address of a cell in the grid\n          return  -->> a Python list of integers, consisting of all\n                       of the cell\'s neighbours\' states";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_listStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  int __pyx_v_i;
  PyObject *__pyx_v_states;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_v_states = Py_None; Py_INCREF(Py_None);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":130 */
  __pyx_1 = PyObject_Length(__pyx_v_address); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_2 = (!(__pyx_1 == 2));
  if (__pyx_2) {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_E); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_InvalidAddressError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_INCREF(__pyx_v_address);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_address);
    Py_INCREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    PyTuple_SET_ITEM(__pyx_3, 1, ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":133 */
  __pyx_4 = PyList_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_v_states);
  __pyx_v_states = __pyx_4;
  __pyx_4 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":135 */
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_5 = PyObject_GetItem(__pyx_v_address, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_address, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_6 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  ((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->__pyx_vtab)->pyx_calculateStates(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self),__pyx_2,__pyx_6);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":137 */
  __pyx_2 = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {
    __pyx_5 = PyObject_GetAttr(__pyx_v_states, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong((((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->neighbors_st[__pyx_v_i])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":140 */
  Py_INCREF(__pyx_v_states);
  __pyx_r = __pyx_v_states;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.listStates");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_states);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static void __pyx_f_12neighborhood_15Neighborhood_2D_pyx_calculateStates(struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_v_self,int __pyx_v_x1,int __pyx_v_x2) {
  int __pyx_v_i;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":152 */
  ((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)__pyx_v_self->__pyx_vtab)->pyx_calculateNeighbors(__pyx_v_self,__pyx_v_x1,__pyx_v_x2);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":153 */
  __pyx_1 = __pyx_v_self->neighbors;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    (__pyx_v_self->neighbors_st[__pyx_v_i]) = ((struct __pyx_vtabstruct_8topology_GridTopology *)__pyx_v_self->topology->__pyx_base.__pyx_vtab)->pyx_get(__pyx_v_self->topology,(__pyx_v_self->neighbors_x1[__pyx_v_i]),(__pyx_v_self->neighbors_x2[__pyx_v_i]));
  }

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_reduceStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_reduceStates[] = "Iterate a binary function recursively on all of a cell\'s\n          neighbours\' states\n\n          address  ---> a Python 2-tuple, the address of a cell in the grid\n          function ---> a Python binary function\n          initialv ---> an initial integer value\n          return   -->> an integer value";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_reduceStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_v_function = 0;
  int __pyx_v_initialv;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"address","function","initialv",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOi", __pyx_argnames, &__pyx_v_address, &__pyx_v_function, &__pyx_v_initialv)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  Py_INCREF(__pyx_v_function);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":166 */
  __pyx_1 = PyObject_Length(__pyx_v_address); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; goto __pyx_L1;}
  __pyx_2 = (!(__pyx_1 == 2));
  if (__pyx_2) {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_E); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_InvalidAddressError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
    Py_INCREF(__pyx_v_address);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_address);
    Py_INCREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    PyTuple_SET_ITEM(__pyx_3, 1, ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":169 */
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_address, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_4 = PyObject_GetItem(__pyx_v_address, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_6 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyInt_FromLong(((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->__pyx_vtab)->pyx_reduceStates(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self),__pyx_2,__pyx_6,__pyx_v_function,__pyx_v_initialv)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.reduceStates");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  Py_DECREF(__pyx_v_function);
  return __pyx_r;
}

static int __pyx_f_12neighborhood_15Neighborhood_2D_pyx_reduceStates(struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_v_self,int __pyx_v_x1,int __pyx_v_x2,PyObject *__pyx_v_function,int __pyx_v_initialv) {
  int __pyx_v_i;
  int __pyx_v_reducing;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_function);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":184 */
  ((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)__pyx_v_self->__pyx_vtab)->pyx_calculateStates(__pyx_v_self,__pyx_v_x1,__pyx_v_x2);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":185 */
  __pyx_v_reducing = __pyx_v_initialv;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":187 */
  __pyx_1 = __pyx_v_self->neighbors;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    __pyx_2 = PyInt_FromLong(__pyx_v_reducing); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong((__pyx_v_self->neighbors_st[__pyx_v_i])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_v_function, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_reducing = __pyx_5;
  }

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":190 */
  __pyx_r = __pyx_v_reducing;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("neighborhood.Neighborhood_2D.pyx_reduceStates");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_function);
  return __pyx_r;
}

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_sumStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_sumStates[] = "Sum all the neighbouring states\n\n          address  ---> a Python 2-tuple, the address of a cell in the grid\n          return -->> an integer value";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_sumStates(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":199 */
  __pyx_1 = PyObject_Length(__pyx_v_address); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 199; goto __pyx_L1;}
  __pyx_2 = (!(__pyx_1 == 2));
  if (__pyx_2) {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_E); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
    __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_InvalidAddressError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
    Py_INCREF(__pyx_v_address);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_address);
    Py_INCREF(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    PyTuple_SET_ITEM(__pyx_3, 1, ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology->__pyx_base.name);
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":202 */
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_address, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_FromLong(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_4 = PyObject_GetItem(__pyx_v_address, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_6 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyInt_FromLong(((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->__pyx_vtab)->pyx_sumStates(((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self),__pyx_2,__pyx_6)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.sumStates");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_add;

static int __pyx_f_12neighborhood_15Neighborhood_2D_pyx_sumStates(struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_v_self,int __pyx_v_x1,int __pyx_v_x2) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_operator); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 212; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_add); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 212; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = ((struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D *)__pyx_v_self->__pyx_vtab)->pyx_reduceStates(__pyx_v_self,__pyx_v_x1,__pyx_v_x2,__pyx_2,0);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_WriteUnraisable("neighborhood.Neighborhood_2D.pyx_sumStates");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_isNormalized;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_isNormalized(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_isNormalized[] = "Check whether a cell\'s address is normalised\n\n          address ---> a grid coordinate value in the form of a Python n-tuple\n          return  -->> True if address is normalised, False otherwise";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_isNormalized(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_isNormalized); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  Py_INCREF(__pyx_v_address);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_address);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.isNormalized");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_normalize;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_normalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_normalize[] = "Normalise an address (depends strongly on the topology chosen)\n\n          address ---> a grid coordinate value in the form of a Python n-tuple\n          return  -->> a standard coordinate value";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_normalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_normalize); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
  Py_INCREF(__pyx_v_address);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_address);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.normalize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_get;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_get[] = "Get the state at a given address\n\n          address ---> a grid coordinate value in the form of a Python n-tuple\n          return  -->> an integer";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_get); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  Py_INCREF(__pyx_v_address);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_address);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_set;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_set[] = "Set a given address to a given state\n\n          address ---> a grid coordinate value in the form of a Python n-tuple\n          state   ---> an integer\n          return  -->> None";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  int __pyx_v_state;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"address","state",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oi", __pyx_argnames, &__pyx_v_address, &__pyx_v_state)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_set); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_state); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
  Py_INCREF(__pyx_v_address);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_address);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_reset;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_reset[] = "Reset a cell to the predefined background state\n\n          address ---> a grid coordinate value in the form of a Python n-tuple\n          return  -->> None";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_reset(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_address = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"address",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_address)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_address);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_reset); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 261; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 261; goto __pyx_L1;}
  Py_INCREF(__pyx_v_address);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_address);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 261; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.reset");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_address);
  return __pyx_r;
}

static PyObject *__pyx_n_center;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_center(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_center[] = "Find a cell located roughly in the center of the grid.\n  \n          return -->> a Python n-tuple, the address of the above cell";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_center(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_center); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 269; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 269; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.center");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_random;

static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_random(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neighborhood_15Neighborhood_2D_random[] = "Find a random, valid address in the grid.        \n  \n          return -->> a Python n-tuple";
static PyObject *__pyx_f_12neighborhood_15Neighborhood_2D_random(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_v_self)->topology), __pyx_n_random); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("neighborhood.Neighborhood_2D.random");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n___init__;

static PyObject *__pyx_k4p;

static char __pyx_k4[] = "Von Neumann neighborhood system";

static int __pyx_f_12neighborhood_22VonNeumannNeighborhood___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_12neighborhood_22VonNeumannNeighborhood___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_8topology_GridTopology *__pyx_v_topology = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"topology",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_topology)) return -1;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF((PyObject *)__pyx_v_topology);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_topology), __pyx_ptype_8topology_GridTopology, 1, "topology")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 285; goto __pyx_L1;}

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":292 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_12neighborhood_Neighborhood_2D), __pyx_n___init__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 292; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 292; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self);
  Py_INCREF(((PyObject *)__pyx_v_topology));
  PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject *)__pyx_v_topology));
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 292; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":293 */
  ((struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *)__pyx_v_self)->__pyx_base.neighbors = 4;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":294 */
  Py_INCREF(__pyx_k4p);
  Py_DECREF(((struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *)__pyx_v_self)->__pyx_base.name);
  ((struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *)__pyx_v_self)->__pyx_base.name = __pyx_k4p;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neighborhood.VonNeumannNeighborhood.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF((PyObject *)__pyx_v_topology);
  return __pyx_r;
}

static struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_f_12neighborhood_22VonNeumannNeighborhood_pyx_clone(struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *__pyx_v_self) {
  struct __pyx_obj_8topology_Topology *__pyx_v_topology_copy;
  struct __pyx_obj_12neighborhood_Neighborhood_2D *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_v_topology_copy = ((struct __pyx_obj_8topology_Topology *)Py_None); Py_INCREF(Py_None);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":303 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_self->__pyx_base.topology), __pyx_n_clone); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_8topology_Topology)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_topology_copy));
  __pyx_v_topology_copy = ((struct __pyx_obj_8topology_Topology *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":304 */
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_topology_copy));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_topology_copy));
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_12neighborhood_VonNeumannNeighborhood), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_12neighborhood_Neighborhood_2D)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L1;}
  __pyx_r = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)Py_None); Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("neighborhood.VonNeumannNeighborhood.pyx_clone");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_topology_copy);
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_12neighborhood_22VonNeumannNeighborhood_pyx_calculateNeighbors(struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *__pyx_v_self,int __pyx_v_x1,int __pyx_v_x2) {
  Py_INCREF((PyObject *)__pyx_v_self);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":315 */
  (__pyx_v_self->__pyx_base.neighbors_x1[0]) = __pyx_v_x1;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":316 */
  (__pyx_v_self->__pyx_base.neighbors_x2[0]) = (__pyx_v_x2 - 1);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":318 */
  (__pyx_v_self->__pyx_base.neighbors_x1[1]) = (__pyx_v_x1 + 1);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":319 */
  (__pyx_v_self->__pyx_base.neighbors_x2[1]) = __pyx_v_x2;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":321 */
  (__pyx_v_self->__pyx_base.neighbors_x1[2]) = __pyx_v_x1;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":322 */
  (__pyx_v_self->__pyx_base.neighbors_x2[2]) = (__pyx_v_x2 + 1);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":324 */
  (__pyx_v_self->__pyx_base.neighbors_x1[3]) = (__pyx_v_x1 - 1);

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":325 */
  (__pyx_v_self->__pyx_base.neighbors_x2[3]) = __pyx_v_x2;

  Py_DECREF((PyObject *)__pyx_v_self);
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_DimensionError, "DimensionError"},
  {&__pyx_n_E, "E"},
  {&__pyx_n_InvalidAddressError, "InvalidAddressError"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_add, "add"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_center, "center"},
  {&__pyx_n_clone, "clone"},
  {&__pyx_n_exceptions_birdcage, "exceptions_birdcage"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_isNormalized, "isNormalized"},
  {&__pyx_n_normalize, "normalize"},
  {&__pyx_n_operator, "operator"},
  {&__pyx_n_random, "random"},
  {&__pyx_n_reset, "reset"},
  {&__pyx_n_set, "set"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {0, 0, 0}
};
static struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D __pyx_vtable_12neighborhood_Neighborhood_2D;

static PyObject *__pyx_tp_new_12neighborhood_Neighborhood_2D(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_12neighborhood_Neighborhood_2D *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_12neighborhood_Neighborhood_2D *)o);
  *(struct __pyx_vtabstruct_12neighborhood_Neighborhood_2D **)&p->__pyx_vtab = __pyx_vtabptr_12neighborhood_Neighborhood_2D;
  p->topology = ((struct __pyx_obj_8topology_GridTopology *)Py_None); Py_INCREF(Py_None);
  p->name = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_12neighborhood_Neighborhood_2D(PyObject *o) {
  struct __pyx_obj_12neighborhood_Neighborhood_2D *p = (struct __pyx_obj_12neighborhood_Neighborhood_2D *)o;
  Py_XDECREF(((PyObject *)p->topology));
  Py_XDECREF(p->name);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_12neighborhood_Neighborhood_2D(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_12neighborhood_Neighborhood_2D *p = (struct __pyx_obj_12neighborhood_Neighborhood_2D *)o;
  if (p->topology) {
    e = (*v)(((PyObject*)p->topology), a); if (e) return e;
  }
  if (p->name) {
    e = (*v)(p->name, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_12neighborhood_Neighborhood_2D(PyObject *o) {
  struct __pyx_obj_12neighborhood_Neighborhood_2D *p = (struct __pyx_obj_12neighborhood_Neighborhood_2D *)o;
  Py_XDECREF(((PyObject *)p->topology));
  p->topology = ((struct __pyx_obj_8topology_GridTopology *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(p->name);
  p->name = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_12neighborhood_Neighborhood_2D[] = {
  {"handleTopology", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_handleTopology, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_handleTopology},
  {"clone", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_clone, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_clone},
  {"listNeighbors", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_listNeighbors, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_listNeighbors},
  {"listStates", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_listStates, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_listStates},
  {"reduceStates", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_reduceStates, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_reduceStates},
  {"sumStates", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_sumStates, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_sumStates},
  {"isNormalized", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_isNormalized, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_isNormalized},
  {"normalize", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_normalize, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_normalize},
  {"get", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_get},
  {"set", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_set, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_set},
  {"reset", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_reset, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_reset},
  {"center", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_center, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_center},
  {"random", (PyCFunction)__pyx_f_12neighborhood_15Neighborhood_2D_random, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neighborhood_15Neighborhood_2D_random},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Neighborhood_2D = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Neighborhood_2D = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Neighborhood_2D = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Neighborhood_2D = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_12neighborhood_Neighborhood_2D = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "neighborhood.Neighborhood_2D", /*tp_name*/
  sizeof(struct __pyx_obj_12neighborhood_Neighborhood_2D), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_12neighborhood_Neighborhood_2D, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Neighborhood_2D, /*tp_as_number*/
  &__pyx_tp_as_sequence_Neighborhood_2D, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Neighborhood_2D, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Neighborhood_2D, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "Base class for all two-dimensional neighborhoods", /*tp_doc*/
  __pyx_tp_traverse_12neighborhood_Neighborhood_2D, /*tp_traverse*/
  __pyx_tp_clear_12neighborhood_Neighborhood_2D, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_12neighborhood_Neighborhood_2D, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_12neighborhood_15Neighborhood_2D___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_12neighborhood_Neighborhood_2D, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_12neighborhood_VonNeumannNeighborhood __pyx_vtable_12neighborhood_VonNeumannNeighborhood;

static PyObject *__pyx_tp_new_12neighborhood_VonNeumannNeighborhood(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *p;
  PyObject *o = __pyx_ptype_12neighborhood_Neighborhood_2D->tp_new(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_12neighborhood_VonNeumannNeighborhood *)o);
  *(struct __pyx_vtabstruct_12neighborhood_VonNeumannNeighborhood **)&p->__pyx_base.__pyx_vtab = __pyx_vtabptr_12neighborhood_VonNeumannNeighborhood;
  return o;
}

static void __pyx_tp_dealloc_12neighborhood_VonNeumannNeighborhood(PyObject *o) {
  __pyx_ptype_12neighborhood_Neighborhood_2D->tp_dealloc(o);
}

static int __pyx_tp_traverse_12neighborhood_VonNeumannNeighborhood(PyObject *o, visitproc v, void *a) {
  int e;
  e = __pyx_ptype_12neighborhood_Neighborhood_2D->tp_traverse(o, v, a); if (e) return e;
  return 0;
}

static int __pyx_tp_clear_12neighborhood_VonNeumannNeighborhood(PyObject *o) {
  __pyx_ptype_12neighborhood_Neighborhood_2D->tp_clear(o);
  return 0;
}

static struct PyMethodDef __pyx_methods_12neighborhood_VonNeumannNeighborhood[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_VonNeumannNeighborhood = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_VonNeumannNeighborhood = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_VonNeumannNeighborhood = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_VonNeumannNeighborhood = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_12neighborhood_VonNeumannNeighborhood = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "neighborhood.VonNeumannNeighborhood", /*tp_name*/
  sizeof(struct __pyx_obj_12neighborhood_VonNeumannNeighborhood), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_12neighborhood_VonNeumannNeighborhood, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_VonNeumannNeighborhood, /*tp_as_number*/
  &__pyx_tp_as_sequence_VonNeumannNeighborhood, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_VonNeumannNeighborhood, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_VonNeumannNeighborhood, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "A 2-D neighborhood system which only looks at the adjacent\n     cells in the 4 cardinal directions", /*tp_doc*/
  __pyx_tp_traverse_12neighborhood_VonNeumannNeighborhood, /*tp_traverse*/
  __pyx_tp_clear_12neighborhood_VonNeumannNeighborhood, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_12neighborhood_VonNeumannNeighborhood, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_12neighborhood_22VonNeumannNeighborhood___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_12neighborhood_VonNeumannNeighborhood, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initneighborhood(void); /*proto*/
PyMODINIT_FUNC initneighborhood(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("neighborhood", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;};
  __pyx_vtabptr_12neighborhood_Neighborhood_2D = &__pyx_vtable_12neighborhood_Neighborhood_2D;
  *(void(**)(void))&__pyx_vtable_12neighborhood_Neighborhood_2D.pyx_clone = (void(*)(void))__pyx_f_12neighborhood_15Neighborhood_2D_pyx_clone;
  *(void(**)(void))&__pyx_vtable_12neighborhood_Neighborhood_2D.pyx_calculateNeighbors = (void(*)(void))__pyx_f_12neighborhood_15Neighborhood_2D_pyx_calculateNeighbors;
  *(void(**)(void))&__pyx_vtable_12neighborhood_Neighborhood_2D.pyx_calculateStates = (void(*)(void))__pyx_f_12neighborhood_15Neighborhood_2D_pyx_calculateStates;
  *(void(**)(void))&__pyx_vtable_12neighborhood_Neighborhood_2D.pyx_reduceStates = (void(*)(void))__pyx_f_12neighborhood_15Neighborhood_2D_pyx_reduceStates;
  *(void(**)(void))&__pyx_vtable_12neighborhood_Neighborhood_2D.pyx_sumStates = (void(*)(void))__pyx_f_12neighborhood_15Neighborhood_2D_pyx_sumStates;
  __pyx_type_12neighborhood_Neighborhood_2D.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_12neighborhood_Neighborhood_2D) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_12neighborhood_Neighborhood_2D.tp_dict, __pyx_vtabptr_12neighborhood_Neighborhood_2D) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Neighborhood_2D", (PyObject *)&__pyx_type_12neighborhood_Neighborhood_2D) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_ptype_12neighborhood_Neighborhood_2D = &__pyx_type_12neighborhood_Neighborhood_2D;
  __pyx_vtabptr_12neighborhood_VonNeumannNeighborhood = &__pyx_vtable_12neighborhood_VonNeumannNeighborhood;
  __pyx_vtable_12neighborhood_VonNeumannNeighborhood.__pyx_base = *__pyx_vtabptr_12neighborhood_Neighborhood_2D;
  *(void(**)(void))&__pyx_vtable_12neighborhood_VonNeumannNeighborhood.__pyx_base.pyx_clone = (void(*)(void))__pyx_f_12neighborhood_22VonNeumannNeighborhood_pyx_clone;
  *(void(**)(void))&__pyx_vtable_12neighborhood_VonNeumannNeighborhood.__pyx_base.pyx_calculateNeighbors = (void(*)(void))__pyx_f_12neighborhood_22VonNeumannNeighborhood_pyx_calculateNeighbors;
  __pyx_type_12neighborhood_VonNeumannNeighborhood.tp_base = __pyx_ptype_12neighborhood_Neighborhood_2D;
  if (PyType_Ready(&__pyx_type_12neighborhood_VonNeumannNeighborhood) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 281; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_12neighborhood_VonNeumannNeighborhood.tp_dict, __pyx_vtabptr_12neighborhood_VonNeumannNeighborhood) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 281; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "VonNeumannNeighborhood", (PyObject *)&__pyx_type_12neighborhood_VonNeumannNeighborhood) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 281; goto __pyx_L1;}
  __pyx_ptype_12neighborhood_VonNeumannNeighborhood = &__pyx_type_12neighborhood_VonNeumannNeighborhood;
  __pyx_ptype_8topology_Topology = __Pyx_ImportType("topology", "Topology", sizeof(struct __pyx_obj_8topology_Topology)); if (!__pyx_ptype_8topology_Topology) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 13; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_8topology_Topology->tp_dict, &__pyx_vtabptr_8topology_Topology) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_ptype_8topology_GridTopology = __Pyx_ImportType("topology", "GridTopology", sizeof(struct __pyx_obj_8topology_GridTopology)); if (!__pyx_ptype_8topology_GridTopology) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 24; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_8topology_GridTopology->tp_dict, &__pyx_vtabptr_8topology_GridTopology) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_ptype_8topology_ToroidTopology = __Pyx_ImportType("topology", "ToroidTopology", sizeof(struct __pyx_obj_8topology_ToroidTopology)); if (!__pyx_ptype_8topology_ToroidTopology) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 44; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_8topology_ToroidTopology->tp_dict, &__pyx_vtabptr_8topology_ToroidTopology) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 44; goto __pyx_L1;}

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":24 */
  __pyx_1 = __Pyx_Import(__pyx_n_exceptions_birdcage, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_E, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":25 */
  __pyx_1 = __Pyx_Import(__pyx_n_operator, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_operator, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/panx/Desktop/birdcage0.5.4/neighborhood.pyx":307 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neighborhood");
}

static char *__pyx_filenames[] = {
  "neighborhood.pyx",
  "topology.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    return PyImport_Import(py_name);
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
