# birdcage is the cellular automaton engine at the root of Project Ouroborus'
# artifical life system. It is based on the cage Python library written by
# Erik Max Francis.

# The original Python code was ported to Pyrex for optimisation. Currently
# the birdcage implementation is limited to 2-dimensional automata and
# incorporates simple agents.

# Birdcage has been successfully compiled and executed using gcc under MinGW
# in a Windows box. It also compiles and runs in Ubuntu.

# Before importing make sure you add the directory containing this file to
# the PYTHONPATH environment variable.
 
# Ang sang waheguru.
# Every cell vibrates God's infinity.


# Here are the components which comprise the current version of birdcage:

#   __init__.py           this file - duh!
#   topology.pyx          the underlying cellular grid for the automaton
#   neighborhood.pyx      a way of defining and relating to a cell's neighbours
#   rule.pyx              the calculation rules for each state transition
#   agent.pyx             simple, autonomous entities which interact with the grid
#   automaton.pyx         the encapsulation of all the components in a coherent unit
#   birdcage_roadmap.txt  a detailed history of development and future plans
#   plus the corresponding .pxd (Pyrex declarations), setup_FILENAME.py,
#   .c (c code generated by Pyrex) and .pyd (compiled binaties) files

# In order to compile from source use the following shell command:

# python setup_FILENAME.py build_ext --inplace

# For more information visit http://ouroborus.sf.net



__name__ = 'birdcage'
__version__ = '0.5.2'
__author__ = 'Sat Tara S Khalsa <smonkey@prodigy.net.mx>'
__copyright__ = 'Copyright 2006 (C) Project Ouroboros'
__license__ = 'GPL'
